/*
Deployment script for msdb

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "msdb"
:setvar DefaultFilePrefix "msdb"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping User-Defined Table Type [dbo].[syspolicy_target_filters_type]...';


GO
DROP TYPE [dbo].[syspolicy_target_filters_type];


GO
PRINT N'Dropping XML Schema Collection [dbo].[schema_collection_Generic SQL Trace Collector Type]...';


GO
DROP XML SCHEMA COLLECTION [dbo].[schema_collection_Generic SQL Trace Collector Type];


GO
PRINT N'Dropping XML Schema Collection [dbo].[schema_collection_Generic T-SQL Query Collector Type]...';


GO
DROP XML SCHEMA COLLECTION [dbo].[schema_collection_Generic T-SQL Query Collector Type];


GO
PRINT N'Dropping XML Schema Collection [dbo].[schema_collection_Performance Counters Collector Type]...';


GO
DROP XML SCHEMA COLLECTION [dbo].[schema_collection_Performance Counters Collector Type];


GO
PRINT N'Dropping XML Schema Collection [dbo].[schema_collection_Query Activity Collector Type]...';


GO
DROP XML SCHEMA COLLECTION [dbo].[schema_collection_Query Activity Collector Type];


GO
PRINT N'Dropping Role Membership [db_ssisltduser] for [dc_operator]...';


GO
EXECUTE sp_droprolemember @rolename = N'db_ssisltduser', @membername = N'dc_operator';


GO
PRINT N'Dropping Role Membership [db_ssisltduser] for [dc_proxy]...';


GO
EXECUTE sp_droprolemember @rolename = N'db_ssisltduser', @membername = N'dc_proxy';


GO
PRINT N'Dropping Role Membership [db_ssisoperator] for [MS_DataCollectorInternalUser]...';


GO
EXECUTE sp_droprolemember @rolename = N'db_ssisoperator', @membername = N'MS_DataCollectorInternalUser';


GO
PRINT N'Dropping Role Membership [db_ssisoperator] for [dc_operator]...';


GO
EXECUTE sp_droprolemember @rolename = N'db_ssisoperator', @membername = N'dc_operator';


GO
PRINT N'Dropping Role Membership [db_ssisoperator] for [dc_proxy]...';


GO
EXECUTE sp_droprolemember @rolename = N'db_ssisoperator', @membername = N'dc_proxy';


GO
PRINT N'Dropping Role Membership [dc_admin] for [MS_DataCollectorInternalUser]...';


GO
EXECUTE sp_droprolemember @rolename = N'dc_admin', @membername = N'MS_DataCollectorInternalUser';


GO
PRINT N'Dropping Role Membership [dc_operator] for [dc_admin]...';


GO
EXECUTE sp_droprolemember @rolename = N'dc_operator', @membername = N'dc_admin';


GO
PRINT N'Dropping Role Membership [ServerGroupReaderRole] for [ServerGroupAdministratorRole]...';


GO
EXECUTE sp_droprolemember @rolename = N'ServerGroupReaderRole', @membername = N'ServerGroupAdministratorRole';


GO
PRINT N'Dropping Role Membership [SQLAgentOperatorRole] for [PolicyAdministratorRole]...';


GO
EXECUTE sp_droprolemember @rolename = N'SQLAgentOperatorRole', @membername = N'PolicyAdministratorRole';


GO
PRINT N'Dropping Role Membership [SQLAgentReaderRole] for [SQLAgentOperatorRole]...';


GO
EXECUTE sp_droprolemember @rolename = N'SQLAgentReaderRole', @membername = N'SQLAgentOperatorRole';


GO
PRINT N'Dropping Role Membership [SQLAgentUserRole] for [SQLAgentReaderRole]...';


GO
EXECUTE sp_droprolemember @rolename = N'SQLAgentUserRole', @membername = N'SQLAgentReaderRole';


GO
PRINT N'Dropping Role Membership [SQLAgentUserRole] for [dc_operator]...';


GO
EXECUTE sp_droprolemember @rolename = N'SQLAgentUserRole', @membername = N'dc_operator';


GO
PRINT N'Dropping Role Membership [SQLAgentUserRole] for [MS_DataCollectorInternalUser]...';


GO
EXECUTE sp_droprolemember @rolename = N'SQLAgentUserRole', @membername = N'MS_DataCollectorInternalUser';


GO
PRINT N'Dropping Role Membership [UtilityIMRReader] for [UtilityIMRWriter]...';


GO
EXECUTE sp_droprolemember @rolename = N'UtilityIMRReader', @membername = N'UtilityIMRWriter';


GO
PRINT N'Dropping User [MS_DataCollectorInternalUser]...';


GO
DROP USER [MS_DataCollectorInternalUser];


GO
PRINT N'Dropping Role [dc_admin]...';


GO
DROP ROLE [dc_admin];


GO
PRINT N'Dropping Role [dc_operator]...';


GO
DROP ROLE [dc_operator];


GO
PRINT N'Dropping Role [dc_proxy]...';


GO
DROP ROLE [dc_proxy];


GO
PRINT N'Dropping Role [PolicyAdministratorRole]...';


GO
DROP ROLE [PolicyAdministratorRole];


GO
PRINT N'Dropping Role [ServerGroupAdministratorRole]...';


GO
DROP ROLE [ServerGroupAdministratorRole];


GO
PRINT N'Dropping Role [ServerGroupReaderRole]...';


GO
DROP ROLE [ServerGroupReaderRole];


GO
PRINT N'Dropping Role [UtilityCMRReader]...';


GO
DROP ROLE [UtilityCMRReader];


GO
PRINT N'Dropping Role [UtilityIMRReader]...';


GO
DROP ROLE [UtilityIMRReader];


GO
PRINT N'Dropping Role [UtilityIMRWriter]...';


GO
DROP ROLE [UtilityIMRWriter];


GO
PRINT N'Dropping Schema [DatabaseMailUserRole]...';


GO
DROP SCHEMA [DatabaseMailUserRole];


GO
PRINT N'Dropping Schema [db_ssisadmin]...';


GO
DROP SCHEMA [db_ssisadmin];


GO
PRINT N'Dropping Schema [db_ssisltduser]...';


GO
DROP SCHEMA [db_ssisltduser];


GO
PRINT N'Dropping Schema [db_ssisoperator]...';


GO
DROP SCHEMA [db_ssisoperator];


GO
PRINT N'Dropping Schema [SQLAgentOperatorRole]...';


GO
DROP SCHEMA [SQLAgentOperatorRole];


GO
PRINT N'Dropping Schema [SQLAgentReaderRole]...';


GO
DROP SCHEMA [SQLAgentReaderRole];


GO
PRINT N'Dropping Schema [SQLAgentUserRole]...';


GO
DROP SCHEMA [SQLAgentUserRole];


GO
PRINT N'Dropping Schema [TargetServersRole]...';


GO
DROP SCHEMA [TargetServersRole];


GO
PRINT N'Dropping Schema [managed_backup]...';


GO
DROP SCHEMA [managed_backup];


GO
PRINT N'Dropping Schema [smart_admin]...';


GO
DROP SCHEMA [smart_admin];


GO
PRINT N'Dropping Role [DatabaseMailUserRole]...';


GO
DROP ROLE [DatabaseMailUserRole];


GO
PRINT N'Dropping Role [db_ssisadmin]...';


GO
DROP ROLE [db_ssisadmin];


GO
PRINT N'Dropping Role [db_ssisltduser]...';


GO
DROP ROLE [db_ssisltduser];


GO
PRINT N'Dropping Role [db_ssisoperator]...';


GO
DROP ROLE [db_ssisoperator];


GO
PRINT N'Dropping Role [SQLAgentOperatorRole]...';


GO
DROP ROLE [SQLAgentOperatorRole];


GO
PRINT N'Dropping Role [SQLAgentReaderRole]...';


GO
DROP ROLE [SQLAgentReaderRole];


GO
PRINT N'Dropping Role [SQLAgentUserRole]...';


GO
DROP ROLE [SQLAgentUserRole];


GO
PRINT N'Dropping Role [TargetServersRole]...';


GO
DROP ROLE [TargetServersRole];


GO
PRINT N'Update complete.';


GO
